[build]
  publish = "output/"
  command = "bash .netlify/build.sh"

[build.environment]
  RUBY_VERSION = "3.0.6"
  HOMEBREW_BUNDLE_FILE = ".netlify/Brewfile"

[context.master]
  command = "bash .netlify/build.sh redirect"

[[redirects]]
  from = "/player/manual"
  to = "https://easyrpg.org/player/manual"
[[redirects]]
  from = "/player/doxydoc"
  to = "https://easyrpg.org/player/doxydoc"
[[redirects]]
  from = "/play"
  to = "https://easyrpg.org/play"
[[redirects]]
  from = "/videos"
  to = "https://easyrpg.org/videos"
[[redirects]]
  from = "/discord"
  to = "https://easyrpg.org/discord"
